//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WikiModel", "FK_ArticleArticle_section", "Articles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Wiki.Models.Articles), "Article_section", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Wiki.Models.Article_section), true)]

#endregion

namespace Wiki.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WikiEntities4 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WikiEntities4 object using the connection string found in the 'WikiEntities4' section of the application configuration file.
        /// </summary>
        public WikiEntities4() : base("name=WikiEntities4", "WikiEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WikiEntities4 object.
        /// </summary>
        public WikiEntities4(string connectionString) : base(connectionString, "WikiEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WikiEntities4 object.
        /// </summary>
        public WikiEntities4(EntityConnection connection) : base(connection, "WikiEntities4")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article__has__Categories> Article__has__Categories
        {
            get
            {
                if ((_Article__has__Categories == null))
                {
                    _Article__has__Categories = base.CreateObjectSet<Article__has__Categories>("Article__has__Categories");
                }
                return _Article__has__Categories;
            }
        }
        private ObjectSet<Article__has__Categories> _Article__has__Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article__has__Keywords> Article__has__Keywords
        {
            get
            {
                if ((_Article__has__Keywords == null))
                {
                    _Article__has__Keywords = base.CreateObjectSet<Article__has__Keywords>("Article__has__Keywords");
                }
                return _Article__has__Keywords;
            }
        }
        private ObjectSet<Article__has__Keywords> _Article__has__Keywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article__has__Tag> Article__has__Tag
        {
            get
            {
                if ((_Article__has__Tag == null))
                {
                    _Article__has__Tag = base.CreateObjectSet<Article__has__Tag>("Article__has__Tag");
                }
                return _Article__has__Tag;
            }
        }
        private ObjectSet<Article__has__Tag> _Article__has__Tag;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Article_section> Article_section
        {
            get
            {
                if ((_Article_section == null))
                {
                    _Article_section = base.CreateObjectSet<Article_section>("Article_section");
                }
                return _Article_section;
            }
        }
        private ObjectSet<Article_section> _Article_section;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Articles> Articles
        {
            get
            {
                if ((_Articles == null))
                {
                    _Articles = base.CreateObjectSet<Articles>("Articles");
                }
                return _Articles;
            }
        }
        private ObjectSet<Articles> _Articles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categories> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Categories>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Categories> _Categories;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Comments> Comments
        {
            get
            {
                if ((_Comments == null))
                {
                    _Comments = base.CreateObjectSet<Comments>("Comments");
                }
                return _Comments;
            }
        }
        private ObjectSet<Comments> _Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Keywords> Keywords
        {
            get
            {
                if ((_Keywords == null))
                {
                    _Keywords = base.CreateObjectSet<Keywords>("Keywords");
                }
                return _Keywords;
            }
        }
        private ObjectSet<Keywords> _Keywords;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tags> Tags
        {
            get
            {
                if ((_Tags == null))
                {
                    _Tags = base.CreateObjectSet<Tags>("Tags");
                }
                return _Tags;
            }
        }
        private ObjectSet<Tags> _Tags;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Users> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<Users>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<Users> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article__has__Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle__has__Categories(Article__has__Categories article__has__Categories)
        {
            base.AddObject("Article__has__Categories", article__has__Categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article__has__Keywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle__has__Keywords(Article__has__Keywords article__has__Keywords)
        {
            base.AddObject("Article__has__Keywords", article__has__Keywords);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article__has__Tag EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle__has__Tag(Article__has__Tag article__has__Tag)
        {
            base.AddObject("Article__has__Tag", article__has__Tag);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Article_section EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticle_section(Article_section article_section)
        {
            base.AddObject("Article_section", article_section);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Articles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArticles(Articles articles)
        {
            base.AddObject("Articles", articles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Categories categories)
        {
            base.AddObject("Categories", categories);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToComments(Comments comments)
        {
            base.AddObject("Comments", comments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Keywords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKeywords(Keywords keywords)
        {
            base.AddObject("Keywords", keywords);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tags EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTags(Tags tags)
        {
            base.AddObject("Tags", tags);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(Users users)
        {
            base.AddObject("Users", users);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Article__has__Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article__has__Categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article__has__Categories object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="article_id">Initial value of the Article_id property.</param>
        /// <param name="categories_id">Initial value of the Categories_id property.</param>
        public static Article__has__Categories CreateArticle__has__Categories(global::System.Int32 id, global::System.Int32 article_id, global::System.Int32 categories_id)
        {
            Article__has__Categories article__has__Categories = new Article__has__Categories();
            article__has__Categories.Id = id;
            article__has__Categories.Article_id = article_id;
            article__has__Categories.Categories_id = categories_id;
            return article__has__Categories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Article_id
        {
            get
            {
                return _Article_id;
            }
            set
            {
                OnArticle_idChanging(value);
                ReportPropertyChanging("Article_id");
                _Article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Article_id");
                OnArticle_idChanged();
            }
        }
        private global::System.Int32 _Article_id;
        partial void OnArticle_idChanging(global::System.Int32 value);
        partial void OnArticle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Categories_id
        {
            get
            {
                return _Categories_id;
            }
            set
            {
                OnCategories_idChanging(value);
                ReportPropertyChanging("Categories_id");
                _Categories_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Categories_id");
                OnCategories_idChanged();
            }
        }
        private global::System.Int32 _Categories_id;
        partial void OnCategories_idChanging(global::System.Int32 value);
        partial void OnCategories_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Article__has__Keywords")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article__has__Keywords : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article__has__Keywords object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="keyword_id">Initial value of the Keyword_id property.</param>
        /// <param name="article_id">Initial value of the Article_id property.</param>
        public static Article__has__Keywords CreateArticle__has__Keywords(global::System.Int32 id, global::System.Int32 keyword_id, global::System.Int32 article_id)
        {
            Article__has__Keywords article__has__Keywords = new Article__has__Keywords();
            article__has__Keywords.Id = id;
            article__has__Keywords.Keyword_id = keyword_id;
            article__has__Keywords.Article_id = article_id;
            return article__has__Keywords;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Keyword_id
        {
            get
            {
                return _Keyword_id;
            }
            set
            {
                OnKeyword_idChanging(value);
                ReportPropertyChanging("Keyword_id");
                _Keyword_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Keyword_id");
                OnKeyword_idChanged();
            }
        }
        private global::System.Int32 _Keyword_id;
        partial void OnKeyword_idChanging(global::System.Int32 value);
        partial void OnKeyword_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Article_id
        {
            get
            {
                return _Article_id;
            }
            set
            {
                OnArticle_idChanging(value);
                ReportPropertyChanging("Article_id");
                _Article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Article_id");
                OnArticle_idChanged();
            }
        }
        private global::System.Int32 _Article_id;
        partial void OnArticle_idChanging(global::System.Int32 value);
        partial void OnArticle_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Article__has__Tag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article__has__Tag : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article__has__Tag object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="article_id">Initial value of the Article_id property.</param>
        /// <param name="tags_id">Initial value of the Tags_id property.</param>
        public static Article__has__Tag CreateArticle__has__Tag(global::System.Int32 id, global::System.Int32 article_id, global::System.Int32 tags_id)
        {
            Article__has__Tag article__has__Tag = new Article__has__Tag();
            article__has__Tag.Id = id;
            article__has__Tag.Article_id = article_id;
            article__has__Tag.Tags_id = tags_id;
            return article__has__Tag;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Article_id
        {
            get
            {
                return _Article_id;
            }
            set
            {
                OnArticle_idChanging(value);
                ReportPropertyChanging("Article_id");
                _Article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Article_id");
                OnArticle_idChanged();
            }
        }
        private global::System.Int32 _Article_id;
        partial void OnArticle_idChanging(global::System.Int32 value);
        partial void OnArticle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Tags_id
        {
            get
            {
                return _Tags_id;
            }
            set
            {
                OnTags_idChanging(value);
                ReportPropertyChanging("Tags_id");
                _Tags_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tags_id");
                OnTags_idChanged();
            }
        }
        private global::System.Int32 _Tags_id;
        partial void OnTags_idChanging(global::System.Int32 value);
        partial void OnTags_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Article_section")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Article_section : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Article_section object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="article_id">Initial value of the Article_id property.</param>
        /// <param name="user_name">Initial value of the User_name property.</param>
        public static Article_section CreateArticle_section(global::System.Int32 id, global::System.Int32 article_id, global::System.String user_name)
        {
            Article_section article_section = new Article_section();
            article_section.Id = id;
            article_section.Article_id = article_id;
            article_section.User_name = user_name;
            return article_section;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Section_heading
        {
            get
            {
                return _Section_heading;
            }
            set
            {
                OnSection_headingChanging(value);
                ReportPropertyChanging("Section_heading");
                _Section_heading = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Section_heading");
                OnSection_headingChanged();
            }
        }
        private global::System.String _Section_heading;
        partial void OnSection_headingChanging(global::System.String value);
        partial void OnSection_headingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Section_text
        {
            get
            {
                return _Section_text;
            }
            set
            {
                OnSection_textChanging(value);
                ReportPropertyChanging("Section_text");
                _Section_text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Section_text");
                OnSection_textChanged();
            }
        }
        private global::System.String _Section_text;
        partial void OnSection_textChanging(global::System.String value);
        partial void OnSection_textChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Parent_section
        {
            get
            {
                return _Parent_section;
            }
            set
            {
                OnParent_sectionChanging(value);
                ReportPropertyChanging("Parent_section");
                _Parent_section = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parent_section");
                OnParent_sectionChanged();
            }
        }
        private Nullable<global::System.Int32> _Parent_section;
        partial void OnParent_sectionChanging(Nullable<global::System.Int32> value);
        partial void OnParent_sectionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Section_order
        {
            get
            {
                return _Section_order;
            }
            set
            {
                OnSection_orderChanging(value);
                ReportPropertyChanging("Section_order");
                _Section_order = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Section_order");
                OnSection_orderChanged();
            }
        }
        private Nullable<global::System.Int32> _Section_order;
        partial void OnSection_orderChanging(Nullable<global::System.Int32> value);
        partial void OnSection_orderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Article_id
        {
            get
            {
                return _Article_id;
            }
            set
            {
                OnArticle_idChanging(value);
                ReportPropertyChanging("Article_id");
                _Article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Article_id");
                OnArticle_idChanged();
            }
        }
        private global::System.Int32 _Article_id;
        partial void OnArticle_idChanging(global::System.Int32 value);
        partial void OnArticle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_name
        {
            get
            {
                return _User_name;
            }
            set
            {
                OnUser_nameChanging(value);
                ReportPropertyChanging("User_name");
                _User_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_name");
                OnUser_nameChanged();
            }
        }
        private global::System.String _User_name;
        partial void OnUser_nameChanging(global::System.String value);
        partial void OnUser_nameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WikiModel", "FK_ArticleArticle_section", "Articles")]
        public Articles Articles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("WikiModel.FK_ArticleArticle_section", "Articles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("WikiModel.FK_ArticleArticle_section", "Articles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Articles> ArticlesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Articles>("WikiModel.FK_ArticleArticle_section", "Articles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Articles>("WikiModel.FK_ArticleArticle_section", "Articles", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Articles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Articles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Articles object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="pub_date">Initial value of the Pub_date property.</param>
        public static Articles CreateArticles(global::System.Int32 id, global::System.String title, global::System.DateTime pub_date)
        {
            Articles articles = new Articles();
            articles.Id = id;
            articles.Title = title;
            articles.Pub_date = pub_date;
            return articles;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Pub_date
        {
            get
            {
                return _Pub_date;
            }
            set
            {
                OnPub_dateChanging(value);
                ReportPropertyChanging("Pub_date");
                _Pub_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pub_date");
                OnPub_dateChanged();
            }
        }
        private global::System.DateTime _Pub_date;
        partial void OnPub_dateChanging(global::System.DateTime value);
        partial void OnPub_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WikiModel", "FK_ArticleArticle_section", "Article_section")]
        public EntityCollection<Article_section> Article_section
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Article_section>("WikiModel.FK_ArticleArticle_section", "Article_section");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Article_section>("WikiModel.FK_ArticleArticle_section", "Article_section", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Categories")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categories : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categories object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="category1">Initial value of the Category1 property.</param>
        public static Categories CreateCategories(global::System.Int32 id, global::System.String category1)
        {
            Categories categories = new Categories();
            categories.Id = id;
            categories.Category1 = category1;
            return categories;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Category1
        {
            get
            {
                return _Category1;
            }
            set
            {
                OnCategory1Changing(value);
                ReportPropertyChanging("Category1");
                _Category1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Category1");
                OnCategory1Changed();
            }
        }
        private global::System.String _Category1;
        partial void OnCategory1Changing(global::System.String value);
        partial void OnCategory1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category_id
        {
            get
            {
                return _Category_id;
            }
            set
            {
                OnCategory_idChanging(value);
                ReportPropertyChanging("Category_id");
                _Category_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category_id");
                OnCategory_idChanged();
            }
        }
        private global::System.String _Category_id;
        partial void OnCategory_idChanging(global::System.String value);
        partial void OnCategory_idChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Comments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Comments object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="user_name">Initial value of the User_name property.</param>
        /// <param name="article_id">Initial value of the Article_id property.</param>
        /// <param name="pub_date">Initial value of the Pub_date property.</param>
        /// <param name="text">Initial value of the text property.</param>
        public static Comments CreateComments(global::System.Int32 id, global::System.String user_name, global::System.Int32 article_id, global::System.DateTime pub_date, global::System.String text)
        {
            Comments comments = new Comments();
            comments.Id = id;
            comments.User_name = user_name;
            comments.Article_id = article_id;
            comments.Pub_date = pub_date;
            comments.text = text;
            return comments;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String User_name
        {
            get
            {
                return _User_name;
            }
            set
            {
                OnUser_nameChanging(value);
                ReportPropertyChanging("User_name");
                _User_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("User_name");
                OnUser_nameChanged();
            }
        }
        private global::System.String _User_name;
        partial void OnUser_nameChanging(global::System.String value);
        partial void OnUser_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Article_id
        {
            get
            {
                return _Article_id;
            }
            set
            {
                OnArticle_idChanging(value);
                ReportPropertyChanging("Article_id");
                _Article_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Article_id");
                OnArticle_idChanged();
            }
        }
        private global::System.Int32 _Article_id;
        partial void OnArticle_idChanging(global::System.Int32 value);
        partial void OnArticle_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Pub_date
        {
            get
            {
                return _Pub_date;
            }
            set
            {
                OnPub_dateChanging(value);
                ReportPropertyChanging("Pub_date");
                _Pub_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pub_date");
                OnPub_dateChanged();
            }
        }
        private global::System.DateTime _Pub_date;
        partial void OnPub_dateChanging(global::System.DateTime value);
        partial void OnPub_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String text
        {
            get
            {
                return _text;
            }
            set
            {
                OntextChanging(value);
                ReportPropertyChanging("text");
                _text = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("text");
                OntextChanged();
            }
        }
        private global::System.String _text;
        partial void OntextChanging(global::System.String value);
        partial void OntextChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Keywords")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Keywords : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Keywords object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="keyword1">Initial value of the Keyword1 property.</param>
        public static Keywords CreateKeywords(global::System.Int32 id, global::System.String description, global::System.String keyword1)
        {
            Keywords keywords = new Keywords();
            keywords.Id = id;
            keywords.Description = description;
            keywords.Keyword1 = keyword1;
            return keywords;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword1
        {
            get
            {
                return _Keyword1;
            }
            set
            {
                OnKeyword1Changing(value);
                ReportPropertyChanging("Keyword1");
                _Keyword1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword1");
                OnKeyword1Changed();
            }
        }
        private global::System.String _Keyword1;
        partial void OnKeyword1Changing(global::System.String value);
        partial void OnKeyword1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Tags")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tags : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tags object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="tag1">Initial value of the Tag1 property.</param>
        public static Tags CreateTags(global::System.Int32 id, global::System.String tag1)
        {
            Tags tags = new Tags();
            tags.Id = id;
            tags.Tag1 = tag1;
            return tags;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag1
        {
            get
            {
                return _Tag1;
            }
            set
            {
                OnTag1Changing(value);
                ReportPropertyChanging("Tag1");
                _Tag1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tag1");
                OnTag1Changed();
            }
        }
        private global::System.String _Tag1;
        partial void OnTag1Changing(global::System.String value);
        partial void OnTag1Changed();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WikiModel", Name="Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Users object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Users CreateUsers(global::System.Int32 id, global::System.String username, global::System.String password)
        {
            Users users = new Users();
            users.Id = id;
            users.Username = username;
            users.Password = password;
            return users;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    
    }

    #endregion
    
}
